version: '3.8'

volumes:
  db:

services:
  php:
    build: docker/php
    container_name: fpm.php
    volumes:
      - ./:/app
    depends_on:
      - db

  nginx:
    build: docker/nginx
    container_name: nginx
    depends_on:
      - php
    volumes:
      - ./:/app
      - ./docker/nginx/vhosts/rest.conf:/etc/nginx/sites-enabled/default
    ports:
      - "8000:80"

  db:
    image: mysql:8.0.31
    restart: always
    environment:
      - MYSQL_DATABASE=buyAndSell
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - '3306:3306'
    volumes:
      - ./docker/data/mysql:/var/lib/mysql

  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - "15672:15672"
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root

#  sphinxsearch:
#    image: sphinx:latest
#    build:
#      context: docker/sphinx
#    volumes:
#      - ./docker/sphinx/sphinx.conf:/etc/sphinxsearch/sphinx.conf
#      - ./docker/sphinx/data:/var/lib/sphinxsearch/data

#  mailhog:
#    image: mailhog/mailhog
#    ports:
#      - '8025:8025'
#      - '1025:1025'
#    restart: always